### ISSUE TITLE
Unicode Error for Tricolore Palette Name

### ISSUE THREAD

**Issue by ross-spencer** [ross-spencer/painter-goblin#5]
```
Painter Goblin is retrieving a #watercolor to paint... 

		SELECT ?item ?itemLabel ?image ?loc ?locLabel ?coll ?collLabel ?artist ?artistLabel ?twitter_loc ?twitter_coll (MD5(CONCAT(str(?item),str(RAND()))) as ?random)  WHERE {
		  ?item wdt:P31 wd:Q18761202.
		  ?item wdt:P18 ?image.
		  OPTIONAL {
	         ?item wdt:P276 ?loc .
			 ?loc wdt:P2002 ?twitter_loc .
	      }
		  ?item wdt:P195 ?coll .
		  ?item wdt:P170 ?artist .
		  OPTIONAL { ?coll wdt:P2002 ?twitter_coll . }
		  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,fr,de,it"}
		} ORDER BY ?random
		LIMIT 1
		
Traceback (most recent call last):
  File "twittergoblin.py", line 238, in <module>
    main()
  File "twittergoblin.py", line 235, in main
    MakeTweet(args.link, args.notweet, style)
  File "twittergoblin.py", line 51, in MakeTweet
    data = wg.maketweet(res, palette_label)
  File "/home/ross-spencer/git/ross-spencer/painter-goblin/wikigoblin.py", line 235, in maketweet
    palette_name + " " + emoji
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 11: ordinal not in range(128)
```

**Comment by ross-spencer** [comment]
FIxed by: https://github.com/ross-spencer/painter-goblin/commit/6c0e3a1d890bc126e5adf15a8ad04555f01b76fd

And: https://github.com/ross-spencer/painter-goblin/commit/7b4326f0990e42a4c7d8f9b7acb6b81b924f2881
